[package]
name = "textual-speedups"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "textual_speedups"
crate-type = ["cdylib"]

[dependencies]
geometry = "0.2.0"
pyo3 = "0.25.0"
